[project]
name = "AoCH"
version = "2024.0.0"
description = "Advent of Code leaderboard for in CH"
dependencies = [
    "flask",
    "requests",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.flit.sdist]
include = ["static/", "templates/"]
